package com.example.marketplace.ui.theme

import androidx.compose.ui.graphics.Color


val marketplace_light_primary = Color(0xFF6A8DCC)
val marketplace_light_onPrimary = Color(0xFFFFFFFF)
val marketplace_light_primaryContainer = Color(0xFFBBC5F1)
val marketplace_light_onPrimaryContainer = Color(0xFF001B3F)
val marketplace_light_secondary = Color(0xFF565E71)
val marketplace_light_onSecondary = Color(0xFFFFFFFF)
val marketplace_light_secondaryContainer = Color(0xFFDAE2F9)
val marketplace_light_onSecondaryContainer = Color(0xFF131C2B)
val marketplace_light_tertiary = Color(0xFF705574)
val marketplace_light_onTertiary = Color(0xFFFFFFFF)
val marketplace_light_tertiaryContainer = Color(0xFFFAD8FD)
val marketplace_light_onTertiaryContainer = Color(0xFF29132E)
val marketplace_light_error = Color(0xFFBA1A1A)
val marketplace_light_errorContainer = Color(0xFFFFDAD6)
val marketplace_light_onError = Color(0xFFFFFFFF)
val marketplace_light_onErrorContainer = Color(0xFF410002)
val marketplace_light_background = Color(0xFFFDFBFF)
val marketplace_light_onBackground = Color(0xFF1A1B1F)
val marketplace_light_surface = Color(0xFFFDFBFF)
val marketplace_light_onSurface = Color(0xFF1A1B1F)
val marketplace_light_surfaceVariant = Color(0xFFE0E2EC)
val marketplace_light_onSurfaceVariant = Color(0xFF7F8186)
val marketplace_light_outline = Color(0xFFD9DADD)
val marketplace_light_inverseOnSurface = Color(0xFFDEDEDF)
val marketplace_light_inverseSurface = Color(0xFF2F3033)
val marketplace_light_inversePrimary = Color(0xFFABC7FF)
val marketplace_light_surfaceTint = Color(0xFF2C5EA7)
val marketplace_light_outlineVariant = Color(0xFFC4C6D0)
val marketplace_light_scrim = Color(0xFF000000)

val marketplace_dark_primary = Color(0xFFABC7FF)
val marketplace_dark_onPrimary = Color(0xFF002F65)
val marketplace_dark_primaryContainer = Color(0xFF02458E)
val marketplace_dark_onPrimaryContainer = Color(0xFFD7E3FF)
val marketplace_dark_secondary = Color(0xFFBEC6DC)
val marketplace_dark_onSecondary = Color(0xFF283041)
val marketplace_dark_secondaryContainer = Color(0xFF3E4759)
val marketplace_dark_onSecondaryContainer = Color(0xFFDAE2F9)
val marketplace_dark_tertiary = Color(0xFFDDBCE0)
val marketplace_dark_onTertiary = Color(0xFF3F2844)
val marketplace_dark_tertiaryContainer = Color(0xFF573E5C)
val marketplace_dark_onTertiaryContainer = Color(0xFFFAD8FD)
val marketplace_dark_error = Color(0xFFFFB4AB)
val marketplace_dark_errorContainer = Color(0xFF93000A)
val marketplace_dark_onError = Color(0xFF690005)
val marketplace_dark_onErrorContainer = Color(0xFFFFDAD6)
val marketplace_dark_background = Color(0xFF1A1B1F)
val marketplace_dark_onBackground = Color(0xFFE3E2E6)
val marketplace_dark_surface = Color(0xFF1A1B1F)
val marketplace_dark_onSurface = Color(0xFFE3E2E6)
val marketplace_dark_surfaceVariant = Color(0xFF44474E)
val marketplace_dark_onSurfaceVariant = Color(0xFFC4C6D0)
val marketplace_dark_outline = Color(0xFF8E9099)
val marketplace_dark_inverseOnSurface = Color(0xFF1A1B1F)
val marketplace_dark_inverseSurface = Color(0xFFE3E2E6)
val marketplace_dark_inversePrimary = Color(0xFF2C5EA7)
val marketplace_dark_surfaceTint = Color(0xFFABC7FF)
val marketplace_dark_outlineVariant = Color(0xFF44474E)
val marketplace_dark_scrim = Color(0xFF000000)

